### ISSUE TITLE
import "@openzeppelin/contracts/..."

### ISSUE THREAD

**Issue by DarrenChangJR** [ucsb-seclab/sailfish#5]
When running Sailfish on contracts that import openzeppelin contracts, it crashes because [Slither uses `crytic-compile` which compiles the contracts using `solc`](https://ethereum.stackexchange.com/a/107492), which doesn't resolve the above imports. However, `crytic-compile` allows for passing in `--solc-remaps <prefix>=<target>`
`slither <path_to_your_contract> --solc-remaps @openzeppelin=node_modules/@openzeppelin`

How did you handle contracts with this import?

**Comment by smartcontract-detect-yzu** [comment]
I meet the same issue.  How to solve this?
